export type AssetType = 'image' | 'video' | 'audio';

export type AudioRole = 'voiceover' | 'music' | 'sfx' | 'ambient' | 'unassigned';

export interface Asset {
  id: string;
  logicalId: string;
  filename: string;
  type: AssetType;
  mimeType: string;
  width?: number;
  height?: number;
  duration?: number;
  url?: string;
  thumbnailUrl?: string;
  filePath?: string;
  serverUrl?: string;
  thumbnail?: string;
  audioRole?: AudioRole;
  sampleRate?: number;
  channels?: number;

  /** Path to browser-compatible proxy file (generated by FFmpeg when native playback fails) */
  proxyFilePath?: string;
  /** URL for the proxy file (docuflow-asset:// URL) */
  proxyUrl?: string;
  /** Whether a proxy was generated for this asset */
  hasProxy?: boolean;
  /** Media probe result from ffprobe (cached for compatibility checks) */
  probeResult?: {
    format?: string;
    videoCodec?: string;
    videoProfile?: string;
    videoPixFmt?: string;
    audioCodec?: string;
    audioProfile?: string;
    audioSampleRate?: number;
    audioChannels?: number;
  };
}
